backend:
  name: git-gateway
  branch: main # Hoặc nhánh chính của bạn

media_folder: "static/images/uploads" # Đường dẫn lưu trữ hình ảnh
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "Genshin/"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
